Add support for read receipts.
filipre/signalbot pull request #53
Opened 2024-05-11 22:24 UTC by brettp

Read receipts for individual messages are available in https://github.com/bbernhard/signal-cli-rest-api/pull/534. This adds support via `Context.receipt("read")`.

2024-05-29 20:03 UTC, filipre requested changes
Thanks for the PR. I left some smaller comments, but I like the feature

2024-05-29 20:03 UTC, filipre commented on signalbot/api.py
> +            raise ReactionError
Should this be a reaction error?

2024-05-29 20:03 UTC, filipre commented on signalbot/api.py
> +        self, recipient: str, receipt_type: str, target_author: str, timestamp: int
It makes sense to introduce literals for parameters like `receipt_type`. I know it can take `read` as a value. What else?

2024-05-29 20:03 UTC, filipre commented on signalbot/bot.py
> +        if getattr(message, 'group'):
This line fails the `pre-commit` hook

2024-05-29 20:03 UTC, filipre commented on signalbot/api.py
> +    def _receipt_rest_uri(self):
to stay consistent with the methods, I'd call it `_receipts_rest_uri` instead

2025-05-29 13:02 UTC, Era-Dorta commented
I've cleaned up and rebased this on top of current master in #125. Thanks a lot for doing this anyway.

2025-05-29 13:02 UTC, closed without merging